services:
  - type: web
    runtime: node
    name: clinic-catalyst-assessment
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: ELEVENLABS_AGENT_ID
        value: agent_6001kpa99tm7fm5sk5da7h057s3r
      - key: ELEVENLABS_PHONE_ID
        value: phnum_3501kpvsp97afx0sy9d0pnzhqwnk
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
